// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/podium/api/v1/podium.proto

package podium_api_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{0}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	WorkingString        string   `protobuf:"bytes,1,opt,name=workingString,proto3" json:"workingString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{1}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetWorkingString() string {
	if m != nil {
		return m.WorkingString
	}
	return ""
}

type TotalMembersRequest struct {
	LeaderboardID        string   `protobuf:"bytes,1,opt,name=leaderboardID,proto3" json:"leaderboardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersRequest) Reset()         { *m = TotalMembersRequest{} }
func (m *TotalMembersRequest) String() string { return proto.CompactTextString(m) }
func (*TotalMembersRequest) ProtoMessage()    {}
func (*TotalMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{2}
}

func (m *TotalMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersRequest.Unmarshal(m, b)
}
func (m *TotalMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersRequest.Marshal(b, m, deterministic)
}
func (m *TotalMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersRequest.Merge(m, src)
}
func (m *TotalMembersRequest) XXX_Size() int {
	return xxx_messageInfo_TotalMembersRequest.Size(m)
}
func (m *TotalMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersRequest proto.InternalMessageInfo

func (m *TotalMembersRequest) GetLeaderboardID() string {
	if m != nil {
		return m.LeaderboardID
	}
	return ""
}

type TotalMembersResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersResponse) Reset()         { *m = TotalMembersResponse{} }
func (m *TotalMembersResponse) String() string { return proto.CompactTextString(m) }
func (*TotalMembersResponse) ProtoMessage()    {}
func (*TotalMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{3}
}

func (m *TotalMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersResponse.Unmarshal(m, b)
}
func (m *TotalMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersResponse.Marshal(b, m, deterministic)
}
func (m *TotalMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersResponse.Merge(m, src)
}
func (m *TotalMembersResponse) XXX_Size() int {
	return xxx_messageInfo_TotalMembersResponse.Size(m)
}
func (m *TotalMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersResponse proto.InternalMessageInfo

func (m *TotalMembersResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthCheckRequest)(nil), "podium.api.v1.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "podium.api.v1.HealthCheckResponse")
	proto.RegisterType((*TotalMembersRequest)(nil), "podium.api.v1.TotalMembersRequest")
	proto.RegisterType((*TotalMembersResponse)(nil), "podium.api.v1.TotalMembersResponse")
}

func init() { proto.RegisterFile("proto/podium/api/v1/podium.proto", fileDescriptor_d33144d47ebf9898) }

var fileDescriptor_d33144d47ebf9898 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc8, 0x4f, 0xc9, 0x2c, 0xcd, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0x84,
	0xf2, 0xf4, 0xc0, 0x52, 0x42, 0xbc, 0x50, 0x5e, 0x62, 0x41, 0xa6, 0x5e, 0x99, 0xa1, 0x94, 0x4c,
	0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0x2a, 0x58, 0x69, 0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66,
	0x7e, 0x5e, 0x31, 0x44, 0xb1, 0x92, 0x08, 0x97, 0x90, 0x47, 0x6a, 0x62, 0x4e, 0x49, 0x86, 0x73,
	0x46, 0x6a, 0x72, 0x76, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x92, 0x35, 0x97, 0x30, 0x8a,
	0x68, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x0a, 0x17, 0x6f, 0x79, 0x7e, 0x51, 0x76, 0x66,
	0x5e, 0x7a, 0x70, 0x49, 0x51, 0x66, 0x5e, 0xba, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0xaa,
	0x20, 0x48, 0x73, 0x48, 0x7e, 0x49, 0x62, 0x8e, 0x6f, 0x6a, 0x6e, 0x52, 0x6a, 0x51, 0x31, 0xd4,
	0x4c, 0x90, 0xe6, 0x9c, 0xd4, 0xc4, 0x94, 0xd4, 0xa2, 0xa4, 0xfc, 0xc4, 0xa2, 0x14, 0x4f, 0x17,
	0x98, 0x66, 0x14, 0x41, 0x25, 0x1d, 0x2e, 0x11, 0x54, 0xcd, 0x50, 0xab, 0x45, 0xb8, 0x58, 0x93,
	0xf3, 0x4b, 0xf3, 0x4a, 0xc0, 0xba, 0x58, 0x83, 0x20, 0x1c, 0xa3, 0xa7, 0x8c, 0x5c, 0x9c, 0x01,
	0x60, 0xdf, 0x3a, 0x06, 0x78, 0x0a, 0x85, 0x70, 0x71, 0x23, 0xb9, 0x5a, 0x48, 0x51, 0x0f, 0x25,
	0x20, 0xf4, 0x30, 0xfd, 0x29, 0xa5, 0x84, 0x4f, 0x09, 0xd4, 0xe6, 0x46, 0x46, 0x2e, 0x1e, 0x64,
	0x27, 0x09, 0xa1, 0x6b, 0xc2, 0xe2, 0x59, 0x29, 0x65, 0xbc, 0x6a, 0x20, 0x26, 0x2b, 0x69, 0x34,
	0x5d, 0x7e, 0x32, 0x99, 0x49, 0x49, 0x49, 0x41, 0x3f, 0x47, 0xbf, 0x1a, 0x25, 0x18, 0x6a, 0xf5,
	0x73, 0x21, 0x6a, 0x75, 0xc1, 0xfe, 0x4c, 0x62, 0x03, 0x47, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x08, 0xff, 0xdf, 0x81, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PodiumAPIClient is the client API for PodiumAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodiumAPIClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error)
}

type podiumAPIClient struct {
	cc *grpc.ClientConn
}

func NewPodiumAPIClient(cc *grpc.ClientConn) PodiumAPIClient {
	return &podiumAPIClient{cc}
}

func (c *podiumAPIClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error) {
	out := new(TotalMembersResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/TotalMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodiumAPIServer is the server API for PodiumAPI service.
type PodiumAPIServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	TotalMembers(context.Context, *TotalMembersRequest) (*TotalMembersResponse, error)
}

// UnimplementedPodiumAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPodiumAPIServer struct {
}

func (*UnimplementedPodiumAPIServer) HealthCheck(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedPodiumAPIServer) TotalMembers(ctx context.Context, req *TotalMembersRequest) (*TotalMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalMembers not implemented")
}

func RegisterPodiumAPIServer(s *grpc.Server, srv PodiumAPIServer) {
	s.RegisterService(&_PodiumAPI_serviceDesc, srv)
}

func _PodiumAPI_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_TotalMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).TotalMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/TotalMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).TotalMembers(ctx, req.(*TotalMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PodiumAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podium.api.v1.PodiumAPI",
	HandlerType: (*PodiumAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PodiumAPI_HealthCheck_Handler,
		},
		{
			MethodName: "TotalMembers",
			Handler:    _PodiumAPI_TotalMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/podium/api/v1/podium.proto",
}
