// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/podium/api/v1/podium.proto

/*
Package podium_api_v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package podium_api_v1

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_PodiumAPI_TotalMembers_0(ctx context.Context, marshaler runtime.Marshaler, client PodiumAPIClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq TotalMembersRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["leaderboardID"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "leaderboardID")
	}

	protoReq.LeaderboardID, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "leaderboardID", err)
	}

	msg, err := client.TotalMembers(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// RegisterPodiumAPIHandlerFromEndpoint is same as RegisterPodiumAPIHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterPodiumAPIHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterPodiumAPIHandler(ctx, mux, conn)
}

// RegisterPodiumAPIHandler registers the http handlers for service PodiumAPI to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterPodiumAPIHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterPodiumAPIHandlerClient(ctx, mux, NewPodiumAPIClient(conn))
}

// RegisterPodiumAPIHandlerClient registers the http handlers for service PodiumAPI
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "PodiumAPIClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "PodiumAPIClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "PodiumAPIClient" to call the correct interceptors.
func RegisterPodiumAPIHandlerClient(ctx context.Context, mux *runtime.ServeMux, client PodiumAPIClient) error {

	mux.Handle("POST", pattern_PodiumAPI_TotalMembers_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PodiumAPI_TotalMembers_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PodiumAPI_TotalMembers_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_PodiumAPI_TotalMembers_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1, 2, 2}, []string{"l", "leaderboardID", "members-count"}, ""))
)

var (
	forward_PodiumAPI_TotalMembers_0 = runtime.ForwardResponseMessage
)
