// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/podium/api/v1/podium.proto

package podium_api_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse struct {
	WorkingString        string   `protobuf:"bytes,1,opt,name=working_string,json=workingString,proto3" json:"working_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{0}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetWorkingString() string {
	if m != nil {
		return m.WorkingString
	}
	return ""
}

type StatusResponse struct {
	ErrorRate            float64  `protobuf:"fixed64,1,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetErrorRate() float64 {
	if m != nil {
		return m.ErrorRate
	}
	return 0
}

type RemoveLeaderboardRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLeaderboardRequest) Reset()         { *m = RemoveLeaderboardRequest{} }
func (m *RemoveLeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveLeaderboardRequest) ProtoMessage()    {}
func (*RemoveLeaderboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{2}
}

func (m *RemoveLeaderboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLeaderboardRequest.Unmarshal(m, b)
}
func (m *RemoveLeaderboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLeaderboardRequest.Marshal(b, m, deterministic)
}
func (m *RemoveLeaderboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLeaderboardRequest.Merge(m, src)
}
func (m *RemoveLeaderboardRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveLeaderboardRequest.Size(m)
}
func (m *RemoveLeaderboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLeaderboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLeaderboardRequest proto.InternalMessageInfo

func (m *RemoveLeaderboardRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

type ScoreUpsert struct {
	PublicID             string   `protobuf:"bytes,1,opt,name=publicID,proto3" json:"publicID,omitempty"`
	Score                int64    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreUpsert) Reset()         { *m = ScoreUpsert{} }
func (m *ScoreUpsert) String() string { return proto.CompactTextString(m) }
func (*ScoreUpsert) ProtoMessage()    {}
func (*ScoreUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{3}
}

func (m *ScoreUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreUpsert.Unmarshal(m, b)
}
func (m *ScoreUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreUpsert.Marshal(b, m, deterministic)
}
func (m *ScoreUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreUpsert.Merge(m, src)
}
func (m *ScoreUpsert) XXX_Size() int {
	return xxx_messageInfo_ScoreUpsert.Size(m)
}
func (m *ScoreUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreUpsert proto.InternalMessageInfo

func (m *ScoreUpsert) GetPublicID() string {
	if m != nil {
		return m.PublicID
	}
	return ""
}

func (m *ScoreUpsert) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type ScoreUpserts struct {
	Members              []*ScoreUpsert `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScoreUpserts) Reset()         { *m = ScoreUpserts{} }
func (m *ScoreUpserts) String() string { return proto.CompactTextString(m) }
func (*ScoreUpserts) ProtoMessage()    {}
func (*ScoreUpserts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{4}
}

func (m *ScoreUpserts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreUpserts.Unmarshal(m, b)
}
func (m *ScoreUpserts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreUpserts.Marshal(b, m, deterministic)
}
func (m *ScoreUpserts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreUpserts.Merge(m, src)
}
func (m *ScoreUpserts) XXX_Size() int {
	return xxx_messageInfo_ScoreUpserts.Size(m)
}
func (m *ScoreUpserts) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreUpserts.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreUpserts proto.InternalMessageInfo

func (m *ScoreUpserts) GetMembers() []*ScoreUpsert {
	if m != nil {
		return m.Members
	}
	return nil
}

type BulkUpsertScoresRequest struct {
	LeaderboardId        string        `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	PrevRank             bool          `protobuf:"varint,2,opt,name=prev_rank,json=prevRank,proto3" json:"prev_rank,omitempty"`
	ScoreTTL             string        `protobuf:"bytes,3,opt,name=scoreTTL,proto3" json:"scoreTTL,omitempty"`
	ScoreUpserts         *ScoreUpserts `protobuf:"bytes,4,opt,name=score_upserts,json=scoreUpserts,proto3" json:"score_upserts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BulkUpsertScoresRequest) Reset()         { *m = BulkUpsertScoresRequest{} }
func (m *BulkUpsertScoresRequest) String() string { return proto.CompactTextString(m) }
func (*BulkUpsertScoresRequest) ProtoMessage()    {}
func (*BulkUpsertScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{5}
}

func (m *BulkUpsertScoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkUpsertScoresRequest.Unmarshal(m, b)
}
func (m *BulkUpsertScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkUpsertScoresRequest.Marshal(b, m, deterministic)
}
func (m *BulkUpsertScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkUpsertScoresRequest.Merge(m, src)
}
func (m *BulkUpsertScoresRequest) XXX_Size() int {
	return xxx_messageInfo_BulkUpsertScoresRequest.Size(m)
}
func (m *BulkUpsertScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkUpsertScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkUpsertScoresRequest proto.InternalMessageInfo

func (m *BulkUpsertScoresRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *BulkUpsertScoresRequest) GetPrevRank() bool {
	if m != nil {
		return m.PrevRank
	}
	return false
}

func (m *BulkUpsertScoresRequest) GetScoreTTL() string {
	if m != nil {
		return m.ScoreTTL
	}
	return ""
}

func (m *BulkUpsertScoresRequest) GetScoreUpserts() *ScoreUpserts {
	if m != nil {
		return m.ScoreUpserts
	}
	return nil
}

type MemberResponse struct {
	PublicID             string   `protobuf:"bytes,1,opt,name=publicID,proto3" json:"publicID,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	IntScore             int64    `protobuf:"varint,3,opt,name=int_score,json=intScore,proto3" json:"int_score,omitempty"`
	Rank                 int32    `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	PreviousRank         int32    `protobuf:"varint,5,opt,name=previous_rank,json=previousRank,proto3" json:"previous_rank,omitempty"`
	ExpireAt             int32    `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Position             int32    `protobuf:"varint,7,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberResponse) Reset()         { *m = MemberResponse{} }
func (m *MemberResponse) String() string { return proto.CompactTextString(m) }
func (*MemberResponse) ProtoMessage()    {}
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{6}
}

func (m *MemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberResponse.Unmarshal(m, b)
}
func (m *MemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberResponse.Marshal(b, m, deterministic)
}
func (m *MemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberResponse.Merge(m, src)
}
func (m *MemberResponse) XXX_Size() int {
	return xxx_messageInfo_MemberResponse.Size(m)
}
func (m *MemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberResponse proto.InternalMessageInfo

func (m *MemberResponse) GetPublicID() string {
	if m != nil {
		return m.PublicID
	}
	return ""
}

func (m *MemberResponse) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *MemberResponse) GetIntScore() int64 {
	if m != nil {
		return m.IntScore
	}
	return 0
}

func (m *MemberResponse) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *MemberResponse) GetPreviousRank() int32 {
	if m != nil {
		return m.PreviousRank
	}
	return 0
}

func (m *MemberResponse) GetExpireAt() int32 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *MemberResponse) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type BulkUpsertScoresResponse struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Members              []*MemberResponse `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BulkUpsertScoresResponse) Reset()         { *m = BulkUpsertScoresResponse{} }
func (m *BulkUpsertScoresResponse) String() string { return proto.CompactTextString(m) }
func (*BulkUpsertScoresResponse) ProtoMessage()    {}
func (*BulkUpsertScoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{7}
}

func (m *BulkUpsertScoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkUpsertScoresResponse.Unmarshal(m, b)
}
func (m *BulkUpsertScoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkUpsertScoresResponse.Marshal(b, m, deterministic)
}
func (m *BulkUpsertScoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkUpsertScoresResponse.Merge(m, src)
}
func (m *BulkUpsertScoresResponse) XXX_Size() int {
	return xxx_messageInfo_BulkUpsertScoresResponse.Size(m)
}
func (m *BulkUpsertScoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkUpsertScoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkUpsertScoresResponse proto.InternalMessageInfo

func (m *BulkUpsertScoresResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BulkUpsertScoresResponse) GetMembers() []*MemberResponse {
	if m != nil {
		return m.Members
	}
	return nil
}

type ScoreChange struct {
	Score                int64    `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreChange) Reset()         { *m = ScoreChange{} }
func (m *ScoreChange) String() string { return proto.CompactTextString(m) }
func (*ScoreChange) ProtoMessage()    {}
func (*ScoreChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{8}
}

func (m *ScoreChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreChange.Unmarshal(m, b)
}
func (m *ScoreChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreChange.Marshal(b, m, deterministic)
}
func (m *ScoreChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreChange.Merge(m, src)
}
func (m *ScoreChange) XXX_Size() int {
	return xxx_messageInfo_ScoreChange.Size(m)
}
func (m *ScoreChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreChange.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreChange proto.InternalMessageInfo

func (m *ScoreChange) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type UpsertScoreRequest struct {
	LeaderboardId        string       `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	MemberPublicId       string       `protobuf:"bytes,2,opt,name=member_public_id,json=memberPublicId,proto3" json:"member_public_id,omitempty"`
	PrevRank             bool         `protobuf:"varint,3,opt,name=prev_rank,json=prevRank,proto3" json:"prev_rank,omitempty"`
	ScoreTTL             int32        `protobuf:"varint,4,opt,name=scoreTTL,proto3" json:"scoreTTL,omitempty"`
	ScoreChange          *ScoreChange `protobuf:"bytes,5,opt,name=score_change,json=scoreChange,proto3" json:"score_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpsertScoreRequest) Reset()         { *m = UpsertScoreRequest{} }
func (m *UpsertScoreRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertScoreRequest) ProtoMessage()    {}
func (*UpsertScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{9}
}

func (m *UpsertScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertScoreRequest.Unmarshal(m, b)
}
func (m *UpsertScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertScoreRequest.Marshal(b, m, deterministic)
}
func (m *UpsertScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertScoreRequest.Merge(m, src)
}
func (m *UpsertScoreRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertScoreRequest.Size(m)
}
func (m *UpsertScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertScoreRequest proto.InternalMessageInfo

func (m *UpsertScoreRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *UpsertScoreRequest) GetMemberPublicId() string {
	if m != nil {
		return m.MemberPublicId
	}
	return ""
}

func (m *UpsertScoreRequest) GetPrevRank() bool {
	if m != nil {
		return m.PrevRank
	}
	return false
}

func (m *UpsertScoreRequest) GetScoreTTL() int32 {
	if m != nil {
		return m.ScoreTTL
	}
	return 0
}

func (m *UpsertScoreRequest) GetScoreChange() *ScoreChange {
	if m != nil {
		return m.ScoreChange
	}
	return nil
}

type DefaultMemberResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PublicID             string   `protobuf:"bytes,2,opt,name=publicID,proto3" json:"publicID,omitempty"`
	Score                float64  `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	IntScore             int64    `protobuf:"varint,4,opt,name=int_score,json=intScore,proto3" json:"int_score,omitempty"`
	Rank                 int32    `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	PreviousRank         int32    `protobuf:"varint,6,opt,name=previous_rank,json=previousRank,proto3" json:"previous_rank,omitempty"`
	ExpireAt             int32    `protobuf:"varint,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultMemberResponse) Reset()         { *m = DefaultMemberResponse{} }
func (m *DefaultMemberResponse) String() string { return proto.CompactTextString(m) }
func (*DefaultMemberResponse) ProtoMessage()    {}
func (*DefaultMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{10}
}

func (m *DefaultMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultMemberResponse.Unmarshal(m, b)
}
func (m *DefaultMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultMemberResponse.Marshal(b, m, deterministic)
}
func (m *DefaultMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultMemberResponse.Merge(m, src)
}
func (m *DefaultMemberResponse) XXX_Size() int {
	return xxx_messageInfo_DefaultMemberResponse.Size(m)
}
func (m *DefaultMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultMemberResponse proto.InternalMessageInfo

func (m *DefaultMemberResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DefaultMemberResponse) GetPublicID() string {
	if m != nil {
		return m.PublicID
	}
	return ""
}

func (m *DefaultMemberResponse) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *DefaultMemberResponse) GetIntScore() int64 {
	if m != nil {
		return m.IntScore
	}
	return 0
}

func (m *DefaultMemberResponse) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *DefaultMemberResponse) GetPreviousRank() int32 {
	if m != nil {
		return m.PreviousRank
	}
	return 0
}

func (m *DefaultMemberResponse) GetExpireAt() int32 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

type BasicResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicResponse) Reset()         { *m = BasicResponse{} }
func (m *BasicResponse) String() string { return proto.CompactTextString(m) }
func (*BasicResponse) ProtoMessage()    {}
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{11}
}

func (m *BasicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicResponse.Unmarshal(m, b)
}
func (m *BasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicResponse.Marshal(b, m, deterministic)
}
func (m *BasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicResponse.Merge(m, src)
}
func (m *BasicResponse) XXX_Size() int {
	return xxx_messageInfo_BasicResponse.Size(m)
}
func (m *BasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasicResponse proto.InternalMessageInfo

func (m *BasicResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BasicResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type TotalMembersRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersRequest) Reset()         { *m = TotalMembersRequest{} }
func (m *TotalMembersRequest) String() string { return proto.CompactTextString(m) }
func (*TotalMembersRequest) ProtoMessage()    {}
func (*TotalMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{12}
}

func (m *TotalMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersRequest.Unmarshal(m, b)
}
func (m *TotalMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersRequest.Marshal(b, m, deterministic)
}
func (m *TotalMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersRequest.Merge(m, src)
}
func (m *TotalMembersRequest) XXX_Size() int {
	return xxx_messageInfo_TotalMembersRequest.Size(m)
}
func (m *TotalMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersRequest proto.InternalMessageInfo

func (m *TotalMembersRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

type TotalMembersResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersResponse) Reset()         { *m = TotalMembersResponse{} }
func (m *TotalMembersResponse) String() string { return proto.CompactTextString(m) }
func (*TotalMembersResponse) ProtoMessage()    {}
func (*TotalMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{13}
}

func (m *TotalMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersResponse.Unmarshal(m, b)
}
func (m *TotalMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersResponse.Marshal(b, m, deterministic)
}
func (m *TotalMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersResponse.Merge(m, src)
}
func (m *TotalMembersResponse) XXX_Size() int {
	return xxx_messageInfo_TotalMembersResponse.Size(m)
}
func (m *TotalMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersResponse proto.InternalMessageInfo

func (m *TotalMembersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TotalMembersResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IncrementScoreRequest struct {
	LeaderboardId        string                      `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	MemberPublicId       string                      `protobuf:"bytes,2,opt,name=member_public_id,json=memberPublicId,proto3" json:"member_public_id,omitempty"`
	ScoreTTL             int32                       `protobuf:"varint,3,opt,name=scoreTTL,proto3" json:"scoreTTL,omitempty"`
	Body                 *IncrementScoreRequest_Body `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IncrementScoreRequest) Reset()         { *m = IncrementScoreRequest{} }
func (m *IncrementScoreRequest) String() string { return proto.CompactTextString(m) }
func (*IncrementScoreRequest) ProtoMessage()    {}
func (*IncrementScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{14}
}

func (m *IncrementScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementScoreRequest.Unmarshal(m, b)
}
func (m *IncrementScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementScoreRequest.Marshal(b, m, deterministic)
}
func (m *IncrementScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementScoreRequest.Merge(m, src)
}
func (m *IncrementScoreRequest) XXX_Size() int {
	return xxx_messageInfo_IncrementScoreRequest.Size(m)
}
func (m *IncrementScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementScoreRequest proto.InternalMessageInfo

func (m *IncrementScoreRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *IncrementScoreRequest) GetMemberPublicId() string {
	if m != nil {
		return m.MemberPublicId
	}
	return ""
}

func (m *IncrementScoreRequest) GetScoreTTL() int32 {
	if m != nil {
		return m.ScoreTTL
	}
	return 0
}

func (m *IncrementScoreRequest) GetBody() *IncrementScoreRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type IncrementScoreRequest_Body struct {
	Increment            int64    `protobuf:"varint,1,opt,name=increment,proto3" json:"increment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementScoreRequest_Body) Reset()         { *m = IncrementScoreRequest_Body{} }
func (m *IncrementScoreRequest_Body) String() string { return proto.CompactTextString(m) }
func (*IncrementScoreRequest_Body) ProtoMessage()    {}
func (*IncrementScoreRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{14, 0}
}

func (m *IncrementScoreRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementScoreRequest_Body.Unmarshal(m, b)
}
func (m *IncrementScoreRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementScoreRequest_Body.Marshal(b, m, deterministic)
}
func (m *IncrementScoreRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementScoreRequest_Body.Merge(m, src)
}
func (m *IncrementScoreRequest_Body) XXX_Size() int {
	return xxx_messageInfo_IncrementScoreRequest_Body.Size(m)
}
func (m *IncrementScoreRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementScoreRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementScoreRequest_Body proto.InternalMessageInfo

func (m *IncrementScoreRequest_Body) GetIncrement() int64 {
	if m != nil {
		return m.Increment
	}
	return 0
}

type GetMemberRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	MemberPublicId       string   `protobuf:"bytes,2,opt,name=member_public_id,json=memberPublicId,proto3" json:"member_public_id,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	ScoreTTL             bool     `protobuf:"varint,4,opt,name=scoreTTL,proto3" json:"scoreTTL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{15}
}

func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberRequest.Unmarshal(m, b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(m, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberRequest.Size(m)
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *GetMemberRequest) GetMemberPublicId() string {
	if m != nil {
		return m.MemberPublicId
	}
	return ""
}

func (m *GetMemberRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetMemberRequest) GetScoreTTL() bool {
	if m != nil {
		return m.ScoreTTL
	}
	return false
}

type GetMembersRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	Order                string   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	ScoreTTL             bool     `protobuf:"varint,3,opt,name=scoreTTL,proto3" json:"scoreTTL,omitempty"`
	Ids                  string   `protobuf:"bytes,4,opt,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMembersRequest) Reset()         { *m = GetMembersRequest{} }
func (m *GetMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetMembersRequest) ProtoMessage()    {}
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{16}
}

func (m *GetMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMembersRequest.Unmarshal(m, b)
}
func (m *GetMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMembersRequest.Merge(m, src)
}
func (m *GetMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetMembersRequest.Size(m)
}
func (m *GetMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMembersRequest proto.InternalMessageInfo

func (m *GetMembersRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *GetMembersRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetMembersRequest) GetScoreTTL() bool {
	if m != nil {
		return m.ScoreTTL
	}
	return false
}

func (m *GetMembersRequest) GetIds() string {
	if m != nil {
		return m.Ids
	}
	return ""
}

type GetMembersResponse struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Members              []*MemberResponse `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	NotFound             []string          `protobuf:"bytes,3,rep,name=notFound,proto3" json:"notFound,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMembersResponse) Reset()         { *m = GetMembersResponse{} }
func (m *GetMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GetMembersResponse) ProtoMessage()    {}
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{17}
}

func (m *GetMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMembersResponse.Unmarshal(m, b)
}
func (m *GetMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMembersResponse.Marshal(b, m, deterministic)
}
func (m *GetMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMembersResponse.Merge(m, src)
}
func (m *GetMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GetMembersResponse.Size(m)
}
func (m *GetMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMembersResponse proto.InternalMessageInfo

func (m *GetMembersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetMembersResponse) GetMembers() []*MemberResponse {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GetMembersResponse) GetNotFound() []string {
	if m != nil {
		return m.NotFound
	}
	return nil
}

type RemoveMemberRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	MemberPublicId       string   `protobuf:"bytes,2,opt,name=member_public_id,json=memberPublicId,proto3" json:"member_public_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberRequest) Reset()         { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()    {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{18}
}

func (m *RemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberRequest.Unmarshal(m, b)
}
func (m *RemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *RemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberRequest.Merge(m, src)
}
func (m *RemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberRequest.Size(m)
}
func (m *RemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberRequest proto.InternalMessageInfo

func (m *RemoveMemberRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *RemoveMemberRequest) GetMemberPublicId() string {
	if m != nil {
		return m.MemberPublicId
	}
	return ""
}

type RemoveMembersRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	Ids                  string   `protobuf:"bytes,2,opt,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMembersRequest) Reset()         { *m = RemoveMembersRequest{} }
func (m *RemoveMembersRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveMembersRequest) ProtoMessage()    {}
func (*RemoveMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{19}
}

func (m *RemoveMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMembersRequest.Unmarshal(m, b)
}
func (m *RemoveMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMembersRequest.Marshal(b, m, deterministic)
}
func (m *RemoveMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMembersRequest.Merge(m, src)
}
func (m *RemoveMembersRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveMembersRequest.Size(m)
}
func (m *RemoveMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMembersRequest proto.InternalMessageInfo

func (m *RemoveMembersRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *RemoveMembersRequest) GetIds() string {
	if m != nil {
		return m.Ids
	}
	return ""
}

type GetRankRequest struct {
	LeaderboardId        string   `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	MemberPublicId       string   `protobuf:"bytes,2,opt,name=member_public_id,json=memberPublicId,proto3" json:"member_public_id,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRankRequest) Reset()         { *m = GetRankRequest{} }
func (m *GetRankRequest) String() string { return proto.CompactTextString(m) }
func (*GetRankRequest) ProtoMessage()    {}
func (*GetRankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{20}
}

func (m *GetRankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRankRequest.Unmarshal(m, b)
}
func (m *GetRankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRankRequest.Marshal(b, m, deterministic)
}
func (m *GetRankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRankRequest.Merge(m, src)
}
func (m *GetRankRequest) XXX_Size() int {
	return xxx_messageInfo_GetRankRequest.Size(m)
}
func (m *GetRankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRankRequest proto.InternalMessageInfo

func (m *GetRankRequest) GetLeaderboardId() string {
	if m != nil {
		return m.LeaderboardId
	}
	return ""
}

func (m *GetRankRequest) GetMemberPublicId() string {
	if m != nil {
		return m.MemberPublicId
	}
	return ""
}

func (m *GetRankRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type GetRankResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PublicID             string   `protobuf:"bytes,2,opt,name=publicID,proto3" json:"publicID,omitempty"`
	Rank                 int32    `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRankResponse) Reset()         { *m = GetRankResponse{} }
func (m *GetRankResponse) String() string { return proto.CompactTextString(m) }
func (*GetRankResponse) ProtoMessage()    {}
func (*GetRankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{21}
}

func (m *GetRankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRankResponse.Unmarshal(m, b)
}
func (m *GetRankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRankResponse.Marshal(b, m, deterministic)
}
func (m *GetRankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRankResponse.Merge(m, src)
}
func (m *GetRankResponse) XXX_Size() int {
	return xxx_messageInfo_GetRankResponse.Size(m)
}
func (m *GetRankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRankResponse proto.InternalMessageInfo

func (m *GetRankResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetRankResponse) GetPublicID() string {
	if m != nil {
		return m.PublicID
	}
	return ""
}

func (m *GetRankResponse) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "podium.api.v1.HealthCheckResponse")
	proto.RegisterType((*StatusResponse)(nil), "podium.api.v1.StatusResponse")
	proto.RegisterType((*RemoveLeaderboardRequest)(nil), "podium.api.v1.RemoveLeaderboardRequest")
	proto.RegisterType((*ScoreUpsert)(nil), "podium.api.v1.ScoreUpsert")
	proto.RegisterType((*ScoreUpserts)(nil), "podium.api.v1.ScoreUpserts")
	proto.RegisterType((*BulkUpsertScoresRequest)(nil), "podium.api.v1.BulkUpsertScoresRequest")
	proto.RegisterType((*MemberResponse)(nil), "podium.api.v1.MemberResponse")
	proto.RegisterType((*BulkUpsertScoresResponse)(nil), "podium.api.v1.BulkUpsertScoresResponse")
	proto.RegisterType((*ScoreChange)(nil), "podium.api.v1.ScoreChange")
	proto.RegisterType((*UpsertScoreRequest)(nil), "podium.api.v1.UpsertScoreRequest")
	proto.RegisterType((*DefaultMemberResponse)(nil), "podium.api.v1.DefaultMemberResponse")
	proto.RegisterType((*BasicResponse)(nil), "podium.api.v1.BasicResponse")
	proto.RegisterType((*TotalMembersRequest)(nil), "podium.api.v1.TotalMembersRequest")
	proto.RegisterType((*TotalMembersResponse)(nil), "podium.api.v1.TotalMembersResponse")
	proto.RegisterType((*IncrementScoreRequest)(nil), "podium.api.v1.IncrementScoreRequest")
	proto.RegisterType((*IncrementScoreRequest_Body)(nil), "podium.api.v1.IncrementScoreRequest.Body")
	proto.RegisterType((*GetMemberRequest)(nil), "podium.api.v1.GetMemberRequest")
	proto.RegisterType((*GetMembersRequest)(nil), "podium.api.v1.GetMembersRequest")
	proto.RegisterType((*GetMembersResponse)(nil), "podium.api.v1.GetMembersResponse")
	proto.RegisterType((*RemoveMemberRequest)(nil), "podium.api.v1.RemoveMemberRequest")
	proto.RegisterType((*RemoveMembersRequest)(nil), "podium.api.v1.RemoveMembersRequest")
	proto.RegisterType((*GetRankRequest)(nil), "podium.api.v1.GetRankRequest")
	proto.RegisterType((*GetRankResponse)(nil), "podium.api.v1.GetRankResponse")
}

func init() { proto.RegisterFile("proto/podium/api/v1/podium.proto", fileDescriptor_d33144d47ebf9898) }

var fileDescriptor_d33144d47ebf9898 = []byte{
	// 1183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0x23, 0x45,
	0x13, 0x56, 0x7b, 0xe2, 0xc4, 0x2e, 0x7f, 0xbc, 0xd9, 0x4e, 0xb2, 0xef, 0x68, 0x9c, 0x80, 0xd3,
	0x0e, 0x6c, 0x36, 0x08, 0x9b, 0x64, 0x17, 0x90, 0x96, 0x45, 0x4b, 0xb2, 0x61, 0x97, 0xa0, 0x45,
	0x44, 0x93, 0x70, 0xe2, 0x60, 0x8d, 0xed, 0x4e, 0x32, 0x8a, 0x3d, 0x6d, 0xa6, 0x67, 0x12, 0xa2,
	0x15, 0x1c, 0x16, 0x21, 0x10, 0x57, 0x04, 0x67, 0xc4, 0xdf, 0xe0, 0x57, 0x20, 0x24, 0x6e, 0xdc,
	0xb8, 0xf0, 0x2f, 0xd0, 0x74, 0xb7, 0x3d, 0x1f, 0xf6, 0x38, 0x36, 0x28, 0xdc, 0xa6, 0xaa, 0xab,
	0xa7, 0x9e, 0xaa, 0x7a, 0xba, 0xaa, 0xa0, 0xda, 0x77, 0x99, 0xc7, 0x1a, 0x7d, 0xd6, 0xb1, 0xfd,
	0x5e, 0xc3, 0xea, 0xdb, 0x8d, 0x8b, 0x6d, 0x25, 0xd5, 0xc5, 0x11, 0x2e, 0x29, 0xc9, 0xea, 0xdb,
	0xf5, 0x8b, 0x6d, 0x63, 0xf5, 0x94, 0xb1, 0xd3, 0x2e, 0x15, 0xa6, 0x96, 0xe3, 0x30, 0xcf, 0xf2,
	0x6c, 0xe6, 0x70, 0x69, 0x6c, 0x54, 0xd4, 0xa9, 0x90, 0x5a, 0xfe, 0x49, 0x83, 0xf6, 0xfa, 0xde,
	0x95, 0x3c, 0x24, 0x0f, 0x61, 0xe9, 0x03, 0x6a, 0x75, 0xbd, 0xb3, 0xc7, 0x67, 0xb4, 0x7d, 0x6e,
	0x52, 0xde, 0x67, 0x0e, 0xa7, 0xf8, 0x15, 0x28, 0x5f, 0x32, 0xf7, 0xdc, 0x76, 0x4e, 0x9b, 0xdc,
	0x73, 0x6d, 0xe7, 0x54, 0x47, 0x55, 0xb4, 0x99, 0x37, 0x4b, 0x4a, 0x7b, 0x24, 0x94, 0xa4, 0x01,
	0xe5, 0x23, 0xcf, 0xf2, 0x7c, 0x3e, 0xbc, 0xb8, 0x06, 0x40, 0x5d, 0x97, 0xb9, 0x4d, 0xd7, 0xf2,
	0xa8, 0xb8, 0x84, 0xcc, 0xbc, 0xd0, 0x98, 0x96, 0x47, 0xc9, 0x2e, 0xe8, 0x26, 0xed, 0xb1, 0x0b,
	0xfa, 0x8c, 0x5a, 0x1d, 0xea, 0xb6, 0x98, 0xe5, 0x76, 0x4c, 0xfa, 0x99, 0x4f, 0xb9, 0x17, 0xf8,
	0xec, 0x86, 0xda, 0xa6, 0xdd, 0x19, 0xf8, 0x8c, 0x68, 0x0f, 0x3a, 0xe4, 0x11, 0x14, 0x8e, 0xda,
	0xcc, 0xa5, 0x9f, 0xf4, 0x39, 0x75, 0x3d, 0x6c, 0x40, 0xae, 0xef, 0xb7, 0xba, 0x76, 0xfb, 0x60,
	0x5f, 0xd9, 0x0f, 0x65, 0xbc, 0x0c, 0x59, 0x1e, 0x98, 0xea, 0x99, 0x2a, 0xda, 0xd4, 0x4c, 0x29,
	0x90, 0x7d, 0x28, 0x46, 0x7e, 0xc0, 0xf1, 0x7d, 0x58, 0xe8, 0xd1, 0x5e, 0x8b, 0xba, 0x5c, 0x47,
	0x55, 0x6d, 0xb3, 0xb0, 0x63, 0xd4, 0x63, 0xe9, 0xad, 0x47, 0xac, 0xcd, 0x81, 0x29, 0xf9, 0x05,
	0xc1, 0xff, 0xf7, 0xfc, 0xee, 0xb9, 0xd4, 0x0b, 0x13, 0x3e, 0x5b, 0x24, 0xb8, 0x02, 0xf9, 0xbe,
	0x4b, 0x2f, 0x9a, 0xae, 0xe5, 0x9c, 0x0b, 0x88, 0x39, 0x33, 0x17, 0x28, 0x4c, 0xcb, 0x39, 0x0f,
	0xe2, 0x12, 0x70, 0x8f, 0x8f, 0x9f, 0xe9, 0x9a, 0x8c, 0x6b, 0x20, 0xe3, 0xf7, 0xa0, 0x24, 0xbe,
	0x9b, 0xbe, 0x0c, 0x41, 0x9f, 0xab, 0xa2, 0xcd, 0xc2, 0x4e, 0x25, 0x1d, 0x37, 0x37, 0x8b, 0x3c,
	0x22, 0x91, 0x5f, 0x11, 0x94, 0x3f, 0x12, 0x91, 0x0c, 0x2b, 0x37, 0x75, 0x22, 0x91, 0x4a, 0x64,
	0x80, 0xdf, 0x76, 0xbc, 0xa6, 0x3c, 0xd1, 0x44, 0x8a, 0x73, 0xb6, 0x23, 0x73, 0x81, 0x31, 0xcc,
	0x89, 0xb8, 0x02, 0x68, 0x59, 0x53, 0x7c, 0xe3, 0x1a, 0x94, 0x82, 0xf8, 0x6c, 0xe6, 0x73, 0x19,
	0x74, 0x56, 0x1c, 0x16, 0x07, 0x4a, 0x11, 0x78, 0x05, 0xf2, 0xf4, 0xf3, 0xbe, 0xed, 0xd2, 0xa6,
	0xe5, 0xe9, 0xf3, 0xc2, 0x20, 0x27, 0x15, 0xbb, 0xb2, 0xda, 0x8c, 0xdb, 0x01, 0xbd, 0xf5, 0x05,
	0x79, 0x36, 0x90, 0x49, 0x0f, 0xf4, 0xd1, 0x82, 0xa8, 0xe0, 0x74, 0x58, 0xe0, 0x7e, 0xbb, 0x4d,
	0x39, 0x17, 0xb1, 0xe5, 0xcc, 0x81, 0x88, 0xdf, 0x0e, 0xab, 0x9f, 0x11, 0xd5, 0x5f, 0x4b, 0x64,
	0x31, 0x9e, 0xa6, 0x90, 0x00, 0x35, 0xc5, 0xc3, 0xc7, 0x67, 0x96, 0x73, 0x4a, 0xc3, 0x14, 0xa1,
	0x28, 0xd7, 0xfe, 0x40, 0x80, 0x23, 0x80, 0x66, 0x24, 0xc8, 0x26, 0x2c, 0x4a, 0x6f, 0x4d, 0x59,
	0x89, 0xc0, 0x30, 0x23, 0x0c, 0xcb, 0x52, 0x7f, 0x28, 0x0b, 0x94, 0xa0, 0x92, 0x36, 0x81, 0x4a,
	0xb2, 0x1c, 0x21, 0x95, 0xde, 0x05, 0x49, 0x8c, 0x66, 0x5b, 0x84, 0x21, 0x2a, 0x92, 0xf2, 0x02,
	0x64, 0xa0, 0x66, 0x81, 0x87, 0x02, 0xf9, 0x1d, 0xc1, 0xca, 0x3e, 0x3d, 0xb1, 0xfc, 0xae, 0x97,
	0xa0, 0x53, 0x7a, 0xc6, 0xa3, 0x44, 0xcb, 0xa4, 0x11, 0x4d, 0x4b, 0x25, 0xda, 0x5c, 0x0a, 0xd1,
	0xb2, 0x93, 0x88, 0x36, 0x7f, 0x1d, 0xd1, 0x16, 0xe2, 0x44, 0x23, 0xbb, 0x50, 0xda, 0xb3, 0xb8,
	0xdd, 0x9e, 0x22, 0x9e, 0xdb, 0x30, 0xef, 0x52, 0x8b, 0x33, 0x47, 0x45, 0xa3, 0xa4, 0xa0, 0xb5,
	0x1e, 0x33, 0xcf, 0xea, 0xca, 0xc4, 0xcc, 0xd8, 0x1c, 0xc8, 0x13, 0x58, 0x8e, 0xdf, 0xbe, 0x16,
	0xc7, 0x32, 0x64, 0xdb, 0xcc, 0x77, 0x3c, 0x01, 0x23, 0x6b, 0x4a, 0x81, 0xfc, 0x85, 0x60, 0xe5,
	0xc0, 0x69, 0xbb, 0xb4, 0x47, 0x9d, 0x1b, 0x26, 0x61, 0xb2, 0x65, 0xc5, 0x79, 0x36, 0xd7, 0x62,
	0x9d, 0x2b, 0xd5, 0xa9, 0xee, 0x26, 0xf8, 0x35, 0x16, 0x60, 0x7d, 0x8f, 0x75, 0xae, 0x4c, 0x71,
	0xcd, 0xd8, 0x80, 0xb9, 0x40, 0xc2, 0xab, 0x01, 0x13, 0x94, 0xad, 0x7a, 0x69, 0xa1, 0x82, 0xfc,
	0x80, 0x60, 0xf1, 0x29, 0x1d, 0x32, 0xf1, 0x86, 0xc2, 0x5c, 0x86, 0x2c, 0x73, 0x3b, 0xd4, 0x55,
	0x6d, 0x59, 0x0a, 0x23, 0x8f, 0x2c, 0x17, 0x06, 0x4f, 0xbe, 0x84, 0x5b, 0x43, 0x58, 0xb3, 0x0e,
	0x89, 0xa1, 0xb7, 0x4c, 0x9a, 0x37, 0x2d, 0xee, 0x0d, 0x2f, 0x82, 0x66, 0x77, 0xe4, 0x4c, 0xc8,
	0x9b, 0xc1, 0x27, 0xf9, 0x0a, 0x01, 0x8e, 0x02, 0xb8, 0xb1, 0xa6, 0x18, 0xe0, 0x72, 0x98, 0xf7,
	0x84, 0xf9, 0x4e, 0x47, 0xd7, 0xaa, 0x5a, 0xf0, 0xb6, 0x07, 0x32, 0x39, 0x81, 0x25, 0x39, 0xfb,
	0x6f, 0xb6, 0x3e, 0xe4, 0x63, 0x58, 0x8e, 0xfa, 0x99, 0x35, 0xe1, 0x2a, 0x7d, 0x99, 0x30, 0x7d,
	0x97, 0x50, 0x7e, 0x4a, 0xbd, 0xa0, 0x67, 0xfc, 0xb7, 0x9c, 0x22, 0x9f, 0xc2, 0xff, 0x86, 0x8e,
	0xff, 0x55, 0x5b, 0x1d, 0xf4, 0x48, 0x2d, 0xec, 0x91, 0x3b, 0xdf, 0x14, 0x21, 0x7f, 0x28, 0x8a,
	0xba, 0x7b, 0x78, 0x80, 0x0f, 0xa0, 0x10, 0xd9, 0x03, 0xf1, 0xed, 0xba, 0x5c, 0x1a, 0xeb, 0x83,
	0xa5, 0xb1, 0xfe, 0x7e, 0xb0, 0x34, 0x1a, 0x24, 0xc1, 0x83, 0x71, 0xbb, 0xe3, 0x23, 0x98, 0x97,
	0x4b, 0x61, 0xea, 0x5f, 0x92, 0x6c, 0x4a, 0xec, 0x90, 0x97, 0x70, 0x6b, 0x64, 0x49, 0xc4, 0x77,
	0x12, 0x77, 0xd2, 0xd6, 0x48, 0x63, 0x35, 0x61, 0x18, 0x6b, 0xe3, 0xa4, 0xf2, 0xe2, 0xb7, 0x3f,
	0xbf, 0xcf, 0xac, 0x6c, 0x2d, 0x35, 0xba, 0x8d, 0xe7, 0xf1, 0x1a, 0x7e, 0x81, 0x7f, 0x44, 0xb0,
	0x98, 0x5c, 0x21, 0xf0, 0xab, 0xc9, 0xff, 0x8d, 0x5f, 0xfa, 0x8c, 0x3b, 0xd7, 0xda, 0x29, 0x08,
	0xdb, 0x02, 0xc2, 0x6b, 0x86, 0x31, 0x06, 0x42, 0x43, 0xbc, 0x62, 0xfe, 0x20, 0xbe, 0xdf, 0xe1,
	0x9f, 0x11, 0x14, 0x22, 0xff, 0xc2, 0xeb, 0x09, 0x5f, 0xa3, 0x2b, 0x86, 0xb1, 0x91, 0x30, 0x19,
	0x3b, 0xa5, 0xc9, 0x87, 0x02, 0xcb, 0xbe, 0x71, 0x7f, 0x1c, 0x16, 0xf5, 0xa8, 0x1b, 0xcf, 0x93,
	0x24, 0x56, 0x30, 0x1f, 0xc4, 0x56, 0x07, 0xfc, 0x02, 0x41, 0x31, 0x3a, 0xb2, 0x70, 0x92, 0x2c,
	0x63, 0xa6, 0xa1, 0x51, 0x9b, 0x68, 0xa3, 0x50, 0xde, 0x15, 0x28, 0x6b, 0x78, 0x7d, 0x02, 0xca,
	0xd7, 0xc5, 0xb8, 0xc3, 0x3f, 0x21, 0x28, 0xc7, 0xa7, 0x09, 0xde, 0x98, 0x66, 0xd8, 0x4c, 0x99,
	0xaf, 0x3d, 0x81, 0xe4, 0xe1, 0xce, 0x3f, 0xcb, 0x97, 0x98, 0x65, 0xf8, 0x3b, 0x04, 0xf9, 0x61,
	0x37, 0xc6, 0x2f, 0x27, 0xfc, 0x26, 0xe7, 0xd7, 0x94, 0xc0, 0xde, 0x12, 0xc0, 0xde, 0xc0, 0xf5,
	0xd9, 0x80, 0xe1, 0x0b, 0x80, 0x70, 0x32, 0xe0, 0x6a, 0x1a, 0x98, 0x61, 0xbd, 0xd6, 0x27, 0x58,
	0x28, 0x28, 0x35, 0x01, 0x65, 0x0d, 0x57, 0x26, 0x40, 0xc1, 0xdf, 0x22, 0x28, 0x46, 0xbb, 0xf4,
	0x08, 0x59, 0xc6, 0x8c, 0x8a, 0x6b, 0x9e, 0xb6, 0x4a, 0xc1, 0xd6, 0xac, 0x29, 0xb8, 0x84, 0x52,
	0x6c, 0x5e, 0xe0, 0xda, 0x04, 0x28, 0x7c, 0x3a, 0x2c, 0x2a, 0x07, 0x5b, 0x13, 0x73, 0xf0, 0x35,
	0x82, 0x05, 0xd5, 0xdf, 0xf1, 0xda, 0x68, 0x5e, 0x23, 0x03, 0xc7, 0x78, 0x29, 0xed, 0x58, 0xf9,
	0x7b, 0x47, 0xf8, 0x7b, 0x13, 0xdf, 0x9b, 0x91, 0x97, 0xc1, 0x24, 0x68, 0xcd, 0x8b, 0xf6, 0x7c,
	0xef, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x78, 0x4c, 0x1f, 0x78, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PodiumAPIClient is the client API for PodiumAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodiumAPIClient interface {
	HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	BulkUpsertScores(ctx context.Context, in *BulkUpsertScoresRequest, opts ...grpc.CallOption) (*BulkUpsertScoresResponse, error)
	UpsertScore(ctx context.Context, in *UpsertScoreRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error)
	TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error)
	IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error)
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error)
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*GetMembersResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	GetRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*GetRankResponse, error)
}

type podiumAPIClient struct {
	cc *grpc.ClientConn
}

func NewPodiumAPIClient(cc *grpc.ClientConn) PodiumAPIClient {
	return &podiumAPIClient{cc}
}

func (c *podiumAPIClient) HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/RemoveLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) BulkUpsertScores(ctx context.Context, in *BulkUpsertScoresRequest, opts ...grpc.CallOption) (*BulkUpsertScoresResponse, error) {
	out := new(BulkUpsertScoresResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/BulkUpsertScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) UpsertScore(ctx context.Context, in *UpsertScoreRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error) {
	out := new(DefaultMemberResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/UpsertScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error) {
	out := new(TotalMembersResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/TotalMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error) {
	out := new(DefaultMemberResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/IncrementScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*DefaultMemberResponse, error) {
	out := new(DefaultMemberResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*GetMembersResponse, error) {
	out := new(GetMembersResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/GetMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/RemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/RemoveMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) GetRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*GetRankResponse, error) {
	out := new(GetRankResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/GetRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodiumAPIServer is the server API for PodiumAPI service.
type PodiumAPIServer interface {
	HealthCheck(context.Context, *empty.Empty) (*HealthCheckResponse, error)
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	RemoveLeaderboard(context.Context, *RemoveLeaderboardRequest) (*BasicResponse, error)
	BulkUpsertScores(context.Context, *BulkUpsertScoresRequest) (*BulkUpsertScoresResponse, error)
	UpsertScore(context.Context, *UpsertScoreRequest) (*DefaultMemberResponse, error)
	TotalMembers(context.Context, *TotalMembersRequest) (*TotalMembersResponse, error)
	IncrementScore(context.Context, *IncrementScoreRequest) (*DefaultMemberResponse, error)
	GetMember(context.Context, *GetMemberRequest) (*DefaultMemberResponse, error)
	GetMembers(context.Context, *GetMembersRequest) (*GetMembersResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*BasicResponse, error)
	RemoveMembers(context.Context, *RemoveMembersRequest) (*BasicResponse, error)
	GetRank(context.Context, *GetRankRequest) (*GetRankResponse, error)
}

// UnimplementedPodiumAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPodiumAPIServer struct {
}

func (*UnimplementedPodiumAPIServer) HealthCheck(ctx context.Context, req *empty.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedPodiumAPIServer) Status(ctx context.Context, req *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedPodiumAPIServer) RemoveLeaderboard(ctx context.Context, req *RemoveLeaderboardRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLeaderboard not implemented")
}
func (*UnimplementedPodiumAPIServer) BulkUpsertScores(ctx context.Context, req *BulkUpsertScoresRequest) (*BulkUpsertScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUpsertScores not implemented")
}
func (*UnimplementedPodiumAPIServer) UpsertScore(ctx context.Context, req *UpsertScoreRequest) (*DefaultMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertScore not implemented")
}
func (*UnimplementedPodiumAPIServer) TotalMembers(ctx context.Context, req *TotalMembersRequest) (*TotalMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalMembers not implemented")
}
func (*UnimplementedPodiumAPIServer) IncrementScore(ctx context.Context, req *IncrementScoreRequest) (*DefaultMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementScore not implemented")
}
func (*UnimplementedPodiumAPIServer) GetMember(ctx context.Context, req *GetMemberRequest) (*DefaultMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (*UnimplementedPodiumAPIServer) GetMembers(ctx context.Context, req *GetMembersRequest) (*GetMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembers not implemented")
}
func (*UnimplementedPodiumAPIServer) RemoveMember(ctx context.Context, req *RemoveMemberRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (*UnimplementedPodiumAPIServer) RemoveMembers(ctx context.Context, req *RemoveMembersRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMembers not implemented")
}
func (*UnimplementedPodiumAPIServer) GetRank(ctx context.Context, req *GetRankRequest) (*GetRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRank not implemented")
}

func RegisterPodiumAPIServer(s *grpc.Server, srv PodiumAPIServer) {
	s.RegisterService(&_PodiumAPI_serviceDesc, srv)
}

func _PodiumAPI_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).HealthCheck(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_RemoveLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).RemoveLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/RemoveLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).RemoveLeaderboard(ctx, req.(*RemoveLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_BulkUpsertScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpsertScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).BulkUpsertScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/BulkUpsertScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).BulkUpsertScores(ctx, req.(*BulkUpsertScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_UpsertScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).UpsertScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/UpsertScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).UpsertScore(ctx, req.(*UpsertScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_TotalMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).TotalMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/TotalMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).TotalMembers(ctx, req.(*TotalMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_IncrementScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).IncrementScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/IncrementScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).IncrementScore(ctx, req.(*IncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_RemoveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).RemoveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/RemoveMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).RemoveMembers(ctx, req.(*RemoveMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_GetRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).GetRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/GetRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).GetRank(ctx, req.(*GetRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PodiumAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podium.api.v1.PodiumAPI",
	HandlerType: (*PodiumAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PodiumAPI_HealthCheck_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PodiumAPI_Status_Handler,
		},
		{
			MethodName: "RemoveLeaderboard",
			Handler:    _PodiumAPI_RemoveLeaderboard_Handler,
		},
		{
			MethodName: "BulkUpsertScores",
			Handler:    _PodiumAPI_BulkUpsertScores_Handler,
		},
		{
			MethodName: "UpsertScore",
			Handler:    _PodiumAPI_UpsertScore_Handler,
		},
		{
			MethodName: "TotalMembers",
			Handler:    _PodiumAPI_TotalMembers_Handler,
		},
		{
			MethodName: "IncrementScore",
			Handler:    _PodiumAPI_IncrementScore_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _PodiumAPI_GetMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _PodiumAPI_GetMembers_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _PodiumAPI_RemoveMember_Handler,
		},
		{
			MethodName: "RemoveMembers",
			Handler:    _PodiumAPI_RemoveMembers_Handler,
		},
		{
			MethodName: "GetRank",
			Handler:    _PodiumAPI_GetRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/podium/api/v1/podium.proto",
}
