// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/podium/api/v1/podium.proto

package podium_api_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse struct {
	WorkingString        string   `protobuf:"bytes,1,opt,name=workingString,proto3" json:"workingString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{0}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetWorkingString() string {
	if m != nil {
		return m.WorkingString
	}
	return ""
}

type StatusResponse struct {
	ErrorRate            float64  `protobuf:"fixed64,1,opt,name=errorRate,proto3" json:"errorRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetErrorRate() float64 {
	if m != nil {
		return m.ErrorRate
	}
	return 0
}

type RemoveLeaderboardRequest struct {
	LeaderboardID        string   `protobuf:"bytes,1,opt,name=leaderboardID,proto3" json:"leaderboardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLeaderboardRequest) Reset()         { *m = RemoveLeaderboardRequest{} }
func (m *RemoveLeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveLeaderboardRequest) ProtoMessage()    {}
func (*RemoveLeaderboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{2}
}

func (m *RemoveLeaderboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLeaderboardRequest.Unmarshal(m, b)
}
func (m *RemoveLeaderboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLeaderboardRequest.Marshal(b, m, deterministic)
}
func (m *RemoveLeaderboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLeaderboardRequest.Merge(m, src)
}
func (m *RemoveLeaderboardRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveLeaderboardRequest.Size(m)
}
func (m *RemoveLeaderboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLeaderboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLeaderboardRequest proto.InternalMessageInfo

func (m *RemoveLeaderboardRequest) GetLeaderboardID() string {
	if m != nil {
		return m.LeaderboardID
	}
	return ""
}

type BasicResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicResponse) Reset()         { *m = BasicResponse{} }
func (m *BasicResponse) String() string { return proto.CompactTextString(m) }
func (*BasicResponse) ProtoMessage()    {}
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{3}
}

func (m *BasicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicResponse.Unmarshal(m, b)
}
func (m *BasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicResponse.Marshal(b, m, deterministic)
}
func (m *BasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicResponse.Merge(m, src)
}
func (m *BasicResponse) XXX_Size() int {
	return xxx_messageInfo_BasicResponse.Size(m)
}
func (m *BasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasicResponse proto.InternalMessageInfo

func (m *BasicResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BasicResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type TotalMembersRequest struct {
	LeaderboardID        string   `protobuf:"bytes,1,opt,name=leaderboardID,proto3" json:"leaderboardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersRequest) Reset()         { *m = TotalMembersRequest{} }
func (m *TotalMembersRequest) String() string { return proto.CompactTextString(m) }
func (*TotalMembersRequest) ProtoMessage()    {}
func (*TotalMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{4}
}

func (m *TotalMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersRequest.Unmarshal(m, b)
}
func (m *TotalMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersRequest.Marshal(b, m, deterministic)
}
func (m *TotalMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersRequest.Merge(m, src)
}
func (m *TotalMembersRequest) XXX_Size() int {
	return xxx_messageInfo_TotalMembersRequest.Size(m)
}
func (m *TotalMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersRequest proto.InternalMessageInfo

func (m *TotalMembersRequest) GetLeaderboardID() string {
	if m != nil {
		return m.LeaderboardID
	}
	return ""
}

type TotalMembersResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalMembersResponse) Reset()         { *m = TotalMembersResponse{} }
func (m *TotalMembersResponse) String() string { return proto.CompactTextString(m) }
func (*TotalMembersResponse) ProtoMessage()    {}
func (*TotalMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d33144d47ebf9898, []int{5}
}

func (m *TotalMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalMembersResponse.Unmarshal(m, b)
}
func (m *TotalMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalMembersResponse.Marshal(b, m, deterministic)
}
func (m *TotalMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMembersResponse.Merge(m, src)
}
func (m *TotalMembersResponse) XXX_Size() int {
	return xxx_messageInfo_TotalMembersResponse.Size(m)
}
func (m *TotalMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMembersResponse proto.InternalMessageInfo

func (m *TotalMembersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TotalMembersResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "podium.api.v1.HealthCheckResponse")
	proto.RegisterType((*StatusResponse)(nil), "podium.api.v1.StatusResponse")
	proto.RegisterType((*RemoveLeaderboardRequest)(nil), "podium.api.v1.RemoveLeaderboardRequest")
	proto.RegisterType((*BasicResponse)(nil), "podium.api.v1.BasicResponse")
	proto.RegisterType((*TotalMembersRequest)(nil), "podium.api.v1.TotalMembersRequest")
	proto.RegisterType((*TotalMembersResponse)(nil), "podium.api.v1.TotalMembersResponse")
}

func init() { proto.RegisterFile("proto/podium/api/v1/podium.proto", fileDescriptor_d33144d47ebf9898) }

var fileDescriptor_d33144d47ebf9898 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xdf, 0xaa, 0xd3, 0x40,
	0x10, 0xc6, 0xc9, 0x91, 0x53, 0xed, 0x68, 0x05, 0xd7, 0x72, 0x08, 0xb1, 0x42, 0x89, 0x82, 0x07,
	0xc1, 0x0d, 0xd5, 0x4b, 0x2f, 0xb4, 0xfe, 0xc3, 0x82, 0x42, 0xd9, 0xfa, 0x02, 0x9b, 0x74, 0x4c,
	0x43, 0x93, 0xdd, 0xb8, 0xbb, 0x89, 0x88, 0x78, 0xa1, 0xaf, 0xd0, 0x47, 0xf3, 0x15, 0x7c, 0x10,
	0xe9, 0x26, 0xfd, 0x93, 0xb4, 0x55, 0xce, 0xe5, 0x37, 0x33, 0xdf, 0x7c, 0xbb, 0xf3, 0x83, 0x61,
	0xae, 0xa4, 0x91, 0x41, 0x2e, 0xe7, 0x49, 0x91, 0x05, 0x3c, 0x4f, 0x82, 0x72, 0x54, 0x2b, 0x6a,
	0x5b, 0xa4, 0x57, 0x2b, 0x9e, 0x27, 0xb4, 0x1c, 0x79, 0x83, 0x58, 0xca, 0x38, 0x45, 0x3b, 0xca,
	0x85, 0x90, 0x86, 0x9b, 0x44, 0x0a, 0x5d, 0x0d, 0x7b, 0xf7, 0xea, 0xae, 0x55, 0x61, 0xf1, 0x39,
	0xc0, 0x2c, 0x37, 0xdf, 0xaa, 0xa6, 0xff, 0x1c, 0xee, 0xbe, 0x47, 0x9e, 0x9a, 0xc5, 0xeb, 0x05,
	0x46, 0x4b, 0x86, 0x3a, 0x97, 0x42, 0x23, 0x79, 0x08, 0xbd, 0xaf, 0x52, 0x2d, 0x13, 0x11, 0xcf,
	0x8c, 0x4a, 0x44, 0xec, 0x3a, 0x43, 0xe7, 0xb2, 0xcb, 0x9a, 0x45, 0x9f, 0xc2, 0xed, 0x99, 0xe1,
	0xa6, 0xd0, 0x5b, 0xdf, 0x00, 0xba, 0xa8, 0x94, 0x54, 0x8c, 0x1b, 0xb4, 0x1e, 0x87, 0xed, 0x0a,
	0xfe, 0x4b, 0x70, 0x19, 0x66, 0xb2, 0xc4, 0x0f, 0xc8, 0xe7, 0xa8, 0x42, 0xc9, 0xd5, 0x9c, 0xe1,
	0x97, 0x02, 0xb5, 0x59, 0x27, 0xa6, 0xbb, 0xea, 0xe4, 0xcd, 0x26, 0xb1, 0x51, 0xf4, 0xc7, 0xd0,
	0x7b, 0xc5, 0x75, 0x12, 0x6d, 0x03, 0x5d, 0xb8, 0xae, 0x8b, 0x28, 0x42, 0xad, 0xad, 0xe1, 0x06,
	0xdb, 0x48, 0x72, 0x01, 0x1d, 0x85, 0x5c, 0x4b, 0xe1, 0x9e, 0xd9, 0x4d, 0xb5, 0x5a, 0xff, 0xf8,
	0x93, 0x34, 0x3c, 0xfd, 0x88, 0x59, 0x88, 0x4a, 0x5f, 0x2d, 0xff, 0x1d, 0xf4, 0x9b, 0xe6, 0xff,
	0x3e, 0xa3, 0x0f, 0xe7, 0x91, 0x2c, 0x84, 0xb1, 0xaf, 0x38, 0x67, 0x95, 0x78, 0xba, 0xba, 0x06,
	0xdd, 0xa9, 0x65, 0x38, 0x9e, 0x4e, 0xc8, 0x04, 0x6e, 0xee, 0x41, 0x20, 0x17, 0xb4, 0x22, 0x46,
	0x37, 0xc4, 0xe8, 0xdb, 0x35, 0x31, 0xcf, 0xa7, 0x0d, 0xec, 0xf4, 0x18, 0xb8, 0x17, 0xd0, 0xa9,
	0x90, 0x9c, 0xdc, 0x72, 0xbf, 0xb5, 0xa5, 0x45, 0xb0, 0x84, 0x3b, 0x07, 0x8c, 0xc8, 0xa3, 0x96,
	0xe7, 0x14, 0x45, 0x6f, 0xd0, 0x1a, 0x6c, 0xc0, 0xf2, 0xbd, 0x5f, 0xbf, 0xff, 0xac, 0xce, 0xfa,
	0x8f, 0x49, 0x90, 0x06, 0xdf, 0x1b, 0x87, 0xfd, 0x41, 0x7e, 0x3a, 0x70, 0x6b, 0xff, 0xb4, 0xa4,
	0xfd, 0xdb, 0x23, 0xd0, 0xbc, 0x07, 0xff, 0x9c, 0xa9, 0x53, 0x2f, 0x6d, 0xaa, 0x4f, 0x86, 0x87,
	0xa9, 0x41, 0x56, 0xcd, 0x3e, 0xb1, 0x54, 0xc2, 0x8e, 0x3d, 0xd5, 0xb3, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0xdc, 0x64, 0x02, 0x81, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PodiumAPIClient is the client API for PodiumAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodiumAPIClient interface {
	HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error)
}

type podiumAPIClient struct {
	cc *grpc.ClientConn
}

func NewPodiumAPIClient(cc *grpc.ClientConn) PodiumAPIClient {
	return &podiumAPIClient{cc}
}

func (c *podiumAPIClient) HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/RemoveLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumAPIClient) TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error) {
	out := new(TotalMembersResponse)
	err := c.cc.Invoke(ctx, "/podium.api.v1.PodiumAPI/TotalMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodiumAPIServer is the server API for PodiumAPI service.
type PodiumAPIServer interface {
	HealthCheck(context.Context, *empty.Empty) (*HealthCheckResponse, error)
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	RemoveLeaderboard(context.Context, *RemoveLeaderboardRequest) (*BasicResponse, error)
	TotalMembers(context.Context, *TotalMembersRequest) (*TotalMembersResponse, error)
}

// UnimplementedPodiumAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPodiumAPIServer struct {
}

func (*UnimplementedPodiumAPIServer) HealthCheck(ctx context.Context, req *empty.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedPodiumAPIServer) Status(ctx context.Context, req *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedPodiumAPIServer) RemoveLeaderboard(ctx context.Context, req *RemoveLeaderboardRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLeaderboard not implemented")
}
func (*UnimplementedPodiumAPIServer) TotalMembers(ctx context.Context, req *TotalMembersRequest) (*TotalMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalMembers not implemented")
}

func RegisterPodiumAPIServer(s *grpc.Server, srv PodiumAPIServer) {
	s.RegisterService(&_PodiumAPI_serviceDesc, srv)
}

func _PodiumAPI_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).HealthCheck(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_RemoveLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).RemoveLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/RemoveLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).RemoveLeaderboard(ctx, req.(*RemoveLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumAPI_TotalMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumAPIServer).TotalMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podium.api.v1.PodiumAPI/TotalMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumAPIServer).TotalMembers(ctx, req.(*TotalMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PodiumAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podium.api.v1.PodiumAPI",
	HandlerType: (*PodiumAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PodiumAPI_HealthCheck_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PodiumAPI_Status_Handler,
		},
		{
			MethodName: "RemoveLeaderboard",
			Handler:    _PodiumAPI_RemoveLeaderboard_Handler,
		},
		{
			MethodName: "TotalMembers",
			Handler:    _PodiumAPI_TotalMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/podium/api/v1/podium.proto",
}
