// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: leaderboard/enriching/proto/webhook/v1/podium_webhook.proto

package podium_leaderboard_webhooks_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichLeaderboardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The members to enrich.
	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *EnrichLeaderboardsRequest) Reset() {
	*x = EnrichLeaderboardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrichLeaderboardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLeaderboardsRequest) ProtoMessage() {}

func (x *EnrichLeaderboardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLeaderboardsRequest.ProtoReflect.Descriptor instead.
func (*EnrichLeaderboardsRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichLeaderboardsRequest) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type EnrichLeaderboardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The enriched members.
	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *EnrichLeaderboardsResponse) Reset() {
	*x = EnrichLeaderboardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrichLeaderboardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLeaderboardsResponse) ProtoMessage() {}

func (x *EnrichLeaderboardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLeaderboardsResponse.ProtoReflect.Descriptor instead.
func (*EnrichLeaderboardsResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichLeaderboardsResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The leaderboard's ID.
	LeaderboardId string `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	// The member's ID.
	MemberId string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// The member's scores.
	Scores []*Score `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	// The member's rank in the leaderboard.
	Rank int32 `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	// The member's metadata.
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetLeaderboardId() string {
	if x != nil {
		return x.LeaderboardId
	}
	return ""
}

func (x *Member) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Member) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Member) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Member) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The score value.
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *Score) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto protoreflect.FileDescriptor

var file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x65, 0x6e,
	0x72, 0x69, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x64, 0x69, 0x75, 0x6d, 0x5f,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x19, 0x45,
	0x6e, 0x72, 0x69, 0x63, 0x68, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x3f, 0x0a, 0x1a, 0x45,
	0x6e, 0x72, 0x69, 0x63, 0x68, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0xf0, 0x01, 0x0a,
	0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12,
	0x31, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x1d, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x98,
	0x01, 0x0a, 0x1d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x45,
	0x6e, 0x72, 0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x77, 0x0a, 0x12, 0x45, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1a, 0x2e, 0x45, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x45, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x3a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x22, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x73, 0x2f, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x6f, 0x64,
	0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescOnce sync.Once
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescData = file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDesc
)

func file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescGZIP() []byte {
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescOnce.Do(func() {
		file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescData)
	})
	return file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDescData
}

var file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_goTypes = []interface{}{
	(*EnrichLeaderboardsRequest)(nil),  // 0: EnrichLeaderboardsRequest
	(*EnrichLeaderboardsResponse)(nil), // 1: EnrichLeaderboardsResponse
	(*Member)(nil),                     // 2: Member
	(*Score)(nil),                      // 3: Score
	nil,                                // 4: Member.MetadataEntry
}
var file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_depIdxs = []int32{
	2, // 0: EnrichLeaderboardsRequest.members:type_name -> Member
	2, // 1: EnrichLeaderboardsResponse.members:type_name -> Member
	3, // 2: Member.scores:type_name -> Score
	4, // 3: Member.metadata:type_name -> Member.MetadataEntry
	0, // 4: LeaderboardsEnrichmentService.EnrichLeaderboards:input_type -> EnrichLeaderboardsRequest
	1, // 5: LeaderboardsEnrichmentService.EnrichLeaderboards:output_type -> EnrichLeaderboardsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_init() }
func file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_init() {
	if File_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrichLeaderboardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrichLeaderboardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_goTypes,
		DependencyIndexes: file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_depIdxs,
		MessageInfos:      file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_msgTypes,
	}.Build()
	File_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto = out.File
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_rawDesc = nil
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_goTypes = nil
	file_leaderboard_enriching_proto_webhook_v1_podium_webhook_proto_depIdxs = nil
}
